create schema if not exists modsen;

create table if not exists modsen.orders
(
    id           int primary key generated by default as identity,
    user_id      int references modsen.user (id),
    price        decimal(10, 2) not null,
    cooking_time int            not null,
    order_time   timestamp
);

create table if not exists modsen.order_product
(
    id         int primary key generated by default as identity,
    order_id   int references modsen.orders (id),
    product_id int references modsen.product (id)
);

