create schema if not exists modsen;

create table if not exists modsen.role
(
    id   int primary key generated by default as identity,
    role varchar(50) not null
);

create table if not exists modsen.user
(
    id       int primary key generated by default as identity,
    name     varchar(255)        not null,
    surname  varchar(255)        not null,
    email    varchar(255) unique not null,
    login    varchar(255) unique not null,
    password varchar(255)        not null,
    role_id  int references modsen.role (id),
    sex      int                 not null,
    birthday date                not null
);
