spring:
  application:
    name: api-gateway


  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin,RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
      discovery:
        locator:
          enabled: true
      routes:
#       start users
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/admin/**
#       start product
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/category/**
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/ingredient/**
#       start order
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080