create schema if not exists modsen;

create table if not exists modsen.category
(
    id          int primary key generated by default as identity,
    name        varchar(255) not null,
    description varchar(255) not null
);

create table if not exists modsen.product
(
    id            int primary key generated by default as identity,
    name          varchar(255)   not null,
    weight        int            not null,
    calories      int            not null,
    protein       int            not null,
    fats          int            not null,
    carbs         int            not null,
    price         decimal(10, 2) not null,
    categories_id int references modsen.category (id)
);

create table if not exists modsen.ingredient
(
    id       int primary key generated by default as identity,
    name     varchar(255) not null,
    calories int          not null,
    protein  int          not null,
    fats     int          not null,
    carbs    int          not null
);

create table if not exists modsen.product_ingredient
(
    id            int primary key generated by default as identity,
    ingredient_id int references modsen.ingredient (id),
    product_id    int references modsen.product (id),
    weight        decimal(10, 2)
);

create table if not exists modsen.ingredient_model
(
    id            int primary key generated by default as identity,
    ingredient_id int references modsen.ingredient (id),
    weight        int not null
);